set -g status off
# ===== PREFIXO
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# ===== MOUSE
set -g mouse on

# ===== TERMINAL
set -g default-terminal "xterm-256color"

# ===== BARRA
set -g status on
set -g status-position bottom
set -g status-bg black
set -g status-fg white

# remove [sessão]
set -g status-left ""

# abas minimalistas
set -g window-status-format "#I"
set -g window-status-current-format "#[bold,reverse][ #I ]"

# relógio
set -g status-right " %H:%M "

# ===== ATALHOS (FUNCIONAM NO ALACRITTY)

# nova aba
bind-key -n M-t new-window

# fechar aba
bind-key -n M-r kill-window

# próxima
bind-key -n M-y next-window

# anterior
bind-key -n M-j previous-window


